import type { CarId, RaceMode, RaceResult, TrackId, Weather } from "./types";
import { todayChallenge } from "./daily";

/** Codex 69: keep this file until freeze tree-shake. Do not add online features. */
export const KEEP_CAREER_MODULE = true;

export type CareerEvent = {
  id: string;
  chapter: number;
  chapterHe: string;
  chapterEn: string;
  trackId: TrackId;
  mode: RaceMode;
  nameHe: string;
  nameEn: string;
  night: boolean;
  unlockStars: number;
  gold: number;
  silver: number;
  bronze: number;
  weather?: Weather;
  lineHe?: string;
  lineEn?: string;
};

export const CAR_UNLOCK: Record<CarId, number> = {
  sabra: 0,
  carmel: 4,
  kfir: 8,
  negev: 12,
  yam: 16,
};

export const CAREER: CareerEvent[] = [
  {
    id: "lic-start",
    chapter: 0,
    chapterHe: "רישיון תל אביב",
    chapterEn: "TLV license",
    trackId: "hayarkon",
    mode: "circuit",
    nameHe: "שיעור 1 · הישאר על הכביש",
    nameEn: "Lesson 1 · Stay on the road",
    night: false,
    unlockStars: 0,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "נועם: שלוש הקפות. בלי לרדת לחול.",
    lineEn: "Noam: Three laps. Stay off the sand.",
  },
  {
    id: "lic-brake",
    chapter: 0,
    chapterHe: "רישיון תל אביב",
    chapterEn: "TLV license",
    trackId: "namal",
    mode: "time",
    nameHe: "שיעור 2 · בלימה בנמל",
    nameEn: "Lesson 2 · Port braking",
    night: false,
    unlockStars: 1,
    gold: 88,
    silver: 108,
    bronze: 132,
    lineHe: "מאיה: בלום לפני הפנייה. לא בתוכה.",
    lineEn: "Maya: Brake before the corner. Not in it.",
  },
  {
    id: "lic-drift",
    chapter: 0,
    chapterHe: "רישיון תל אביב",
    chapterEn: "TLV license",
    trackId: "oldjaffa",
    mode: "drift",
    nameHe: "שיעור 3 · אבני יפו",
    nameEn: "Lesson 3 · Jaffa stones",
    night: true,
    unlockStars: 3,
    gold: 7200,
    silver: 4200,
    bronze: 2200,
    lineHe: "ארי: תן לו להחליק. אל תילחם בהגה.",
    lineEn: "Ari: Let it slide. Don't fight the wheel.",
  },
  {
    id: "lic-clean",
    chapter: 0,
    chapterHe: "רישיון תל אביב",
    chapterEn: "TLV license",
    trackId: "rothschild",
    mode: "circuit",
    nameHe: "שיעור 4 · הקפה נקייה",
    nameEn: "Lesson 4 · Clean lap",
    night: false,
    unlockStars: 5,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "תמר: רוטשילד צר. קו אחד, בלי קיר.",
    lineEn: "Tamar: Rothschild is tight. One line, no walls.",
  },
  {
    id: "lic-wet",
    chapter: 0,
    chapterHe: "רישיון תל אביב",
    chapterEn: "TLV license",
    trackId: "ayalon",
    mode: "time",
    nameHe: "שיעור 5 · איילון רטוב",
    nameEn: "Lesson 5 · Wet Ayalon",
    night: true,
    unlockStars: 8,
    gold: 82,
    silver: 102,
    bronze: 126,
    weather: "rain",
    lineHe: "מאיה: שלוליות בצד. תישאר במרכז.",
    lineEn: "Maya: Puddles on the edge. Stay center.",
  },
  {
    id: "lic-heat",
    chapter: 0,
    chapterHe: "רישיון תל אביב",
    chapterEn: "TLV license",
    trackId: "telaviv",
    mode: "heat",
    nameHe: "שיעור 6 · בריחה מאיילון",
    nameEn: "Lesson 6 · Ayalon getaway",
    night: true,
    unlockStars: 11,
    gold: 95,
    silver: 120,
    bronze: 150,
    lineHe: "נועם: שני שוטרים. אל תיגע בהם.",
    lineEn: "Noam: Two cops. Don't tap them.",
  },
  {
    id: "tlv-promenade",
    chapter: 1,
    chapterHe: "תל אביב",
    chapterEn: "Tel Aviv",
    trackId: "hayarkon",
    mode: "circuit",
    nameHe: "טיילת הזהב",
    nameEn: "Golden promenade",
    night: false,
    unlockStars: 0,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "נועם: טיילת. אל תיגע בתיירים.",
    lineEn: "Noam: Promenade. Don't clip the tourists.",
  },
  {
    id: "tlv-azrieli",
    chapter: 1,
    chapterHe: "תל אביב",
    chapterEn: "Tel Aviv",
    trackId: "telaviv",
    mode: "circuit",
    nameHe: "מעגל עזריאלי",
    nameEn: "Azrieli circuit",
    night: false,
    unlockStars: 0,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "מאיה: שלושת המגדלים מימין. תשמור קו.",
    lineEn: "Maya: Three towers on the right. Hold the line.",
  },
  {
    id: "tlv-port-time",
    chapter: 1,
    chapterHe: "תל אביב",
    chapterEn: "Tel Aviv",
    trackId: "namal",
    mode: "time",
    nameHe: "נגד השעון בנמל",
    nameEn: "Port time attack",
    night: true,
    unlockStars: 2,
    gold: 85,
    silver: 105,
    bronze: 130,
    weather: "rain",
  },
  {
    id: "jaffa-drift",
    chapter: 2,
    chapterHe: "יפו והדרום",
    chapterEn: "Jaffa & the south",
    trackId: "oldjaffa",
    mode: "drift",
    nameHe: "דריפט ביפו",
    nameEn: "Jaffa drift",
    night: true,
    unlockStars: 5,
    gold: 9000,
    silver: 5500,
    bronze: 2800,
  },
  {
    id: "jaffa-circuit",
    chapter: 2,
    chapterHe: "יפו והדרום",
    chapterEn: "Jaffa & the south",
    trackId: "oldjaffa",
    mode: "circuit",
    nameHe: "נמל יפו",
    nameEn: "Jaffa port",
    night: false,
    unlockStars: 5,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "tlv-heat",
    chapter: 2,
    chapterHe: "יפו והדרום",
    chapterEn: "Jaffa & the south",
    trackId: "hayarkon",
    mode: "heat",
    nameHe: "מרדף בטיילת",
    nameEn: "Promenade heat",
    night: true,
    unlockStars: 8,
    gold: 90,
    silver: 120,
    bronze: 160,
  },
  {
    id: "jer-gold",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "jerusalem",
    mode: "circuit",
    nameHe: "ירושלים של זהב",
    nameEn: "Jerusalem of gold",
    night: false,
    unlockStars: 11,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "haifa-drop",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "haifa",
    mode: "knockout",
    nameHe: "הדחה בכרמל",
    nameEn: "Carmel knockout",
    night: false,
    unlockStars: 11,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "eilat-time",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "eilat",
    mode: "time",
    nameHe: "קו החוף באילת",
    nameEn: "Eilat shoreline",
    night: false,
    unlockStars: 14,
    gold: 80,
    silver: 100,
    bronze: 125,
  },
  {
    id: "negev-ring",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "beersheva",
    mode: "circuit",
    nameHe: "טבעת הנגב",
    nameEn: "Negev ring",
    night: false,
    unlockStars: 12,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "תמר: חול בצדדים. תישאר על רגר.",
    lineEn: "Tamar: Sand on the edges. Stay on Rager.",
  },
  {
    id: "netanya-cliff",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "netanya",
    mode: "drift",
    nameHe: "דריפט על המצוק",
    nameEn: "Cliff drift",
    night: true,
    unlockStars: 12,
    gold: 8000,
    silver: 4800,
    bronze: 2400,
    lineHe: "ארי: הטיילת צרה. אל תיפול לים.",
    lineEn: "Ari: Tight promenade. Don't drop into the sea.",
  },
  {
    id: "hw1-climb",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "hw1",
    mode: "time",
    nameHe: "עלייה לשער הגיא",
    nameEn: "Sha'ar HaGai climb",
    night: false,
    unlockStars: 14,
    gold: 92,
    silver: 114,
    bronze: 140,
    lineHe: "מאיה: כביש רחב. אל תישן בירידה.",
    lineEn: "Maya: Wide road. Don't sleep on the descent.",
  },
  {
    id: "herz-marina",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "herzliya",
    mode: "heat",
    nameHe: "מרדף במרינה",
    nameEn: "Marina heat",
    night: true,
    unlockStars: 14,
    gold: 100,
    silver: 130,
    bronze: 170,
    lineHe: "נועם: הייטק ויאכטות. המשטרה אוהבת את זה.",
    lineEn: "Noam: Tech and yachts. Cops love this.",
  },
  {
    id: "nyc-neon",
    chapter: 4,
    chapterHe: "ניו יורק",
    chapterEn: "New York",
    trackId: "timessquare",
    mode: "circuit",
    nameHe: "ניאון בטיימס",
    nameEn: "Times Square neon",
    night: true,
    unlockStars: 17,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "nyc-park-drift",
    chapter: 4,
    chapterHe: "ניו יורק",
    chapterEn: "New York",
    trackId: "centralpark",
    mode: "drift",
    nameHe: "דריפט בסנטרל פארק",
    nameEn: "Central Park drift",
    night: false,
    unlockStars: 17,
    gold: 11000,
    silver: 6500,
    bronze: 3200,
  },
  {
    id: "nyc-bridge",
    chapter: 4,
    chapterHe: "ניו יורק",
    chapterEn: "New York",
    trackId: "brooklynbridge",
    mode: "time",
    nameHe: "גשר ברוקלין",
    nameEn: "Brooklyn Bridge run",
    night: true,
    unlockStars: 20,
    gold: 95,
    silver: 120,
    bronze: 150,
  },
  {
    id: "nyc-island-ko",
    chapter: 5,
    chapterHe: "המחתרת",
    chapterEn: "The Underground",
    trackId: "manhattan",
    mode: "knockout",
    nameHe: "הקפת האי",
    nameEn: "Island knockout",
    night: true,
    unlockStars: 24,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "nyc-manhattan-heat",
    chapter: 5,
    chapterHe: "המחתרת",
    chapterEn: "The Underground",
    trackId: "manhattan",
    mode: "heat",
    nameHe: "מרדף במנהטן",
    nameEn: "Manhattan heat",
    night: true,
    unlockStars: 27,
    gold: 140,
    silver: 180,
    bronze: 230,
    weather: "storm",
  },
  {
    id: "nyc-nypd",
    chapter: 5,
    chapterHe: "המחתרת",
    chapterEn: "The Underground",
    trackId: "timessquare",
    mode: "heat",
    nameHe: "משטרת ניו יורק",
    nameEn: "NYPD",
    night: true,
    unlockStars: 30,
    gold: 90,
    silver: 115,
    bronze: 145,
  },
  {
    id: "tlv-ko",
    chapter: 2,
    chapterHe: "יפו והדרום",
    chapterEn: "Jaffa & the south",
    trackId: "telaviv",
    mode: "knockout",
    nameHe: "הדחה באיילון",
    nameEn: "Ayalon knockout",
    night: true,
    unlockStars: 8,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "jer-night",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "jerusalem",
    mode: "time",
    nameHe: "ירושלים בלילה",
    nameEn: "Jerusalem night",
    night: true,
    unlockStars: 13,
    gold: 88,
    silver: 110,
    bronze: 138,
  },
  {
    id: "haifa-night",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "haifa",
    mode: "circuit",
    nameHe: "חיפה בלילה",
    nameEn: "Haifa nights",
    night: true,
    unlockStars: 14,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "eilat-storm",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "eilat",
    mode: "time",
    nameHe: "סערה באילת",
    nameEn: "Eilat storm",
    night: true,
    unlockStars: 16,
    gold: 92,
    silver: 118,
    bronze: 148,
    weather: "storm",
  },
  {
    id: "haifa-heat",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "haifa",
    mode: "heat",
    nameHe: "מרדף בכרמל",
    nameEn: "Carmel heat",
    night: true,
    unlockStars: 18,
    gold: 110,
    silver: 145,
    bronze: 185,
  },
  {
    id: "nyc-park-lap",
    chapter: 4,
    chapterHe: "ניו יורק",
    chapterEn: "New York",
    trackId: "centralpark",
    mode: "circuit",
    nameHe: "לולאת הפארק",
    nameEn: "Park loop",
    night: false,
    unlockStars: 20,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "tlv-rothschild",
    chapter: 1,
    chapterHe: "תל אביב",
    chapterEn: "Tel Aviv",
    trackId: "rothschild",
    mode: "circuit",
    nameHe: "העיר הלבנה",
    nameEn: "White City",
    night: false,
    unlockStars: 3,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "tlv-ayalon",
    chapter: 1,
    chapterHe: "תל אביב",
    chapterEn: "Tel Aviv",
    trackId: "ayalon",
    mode: "time",
    nameHe: "איילון נגד השעון",
    nameEn: "Ayalon attack",
    night: true,
    unlockStars: 4,
    gold: 82,
    silver: 102,
    bronze: 128,
  },
  {
    id: "caesarea-run",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "caesarea",
    mode: "circuit",
    nameHe: "אמת המים",
    nameEn: "The aqueduct",
    night: false,
    unlockStars: 12,
    gold: 1,
    silver: 2,
    bronze: 3,
  },
  {
    id: "deadsea-time",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "deadsea",
    mode: "time",
    nameHe: "מינוס 430",
    nameEn: "Minus 430",
    night: false,
    unlockStars: 14,
    gold: 86,
    silver: 108,
    bronze: 136,
  },
  {
    id: "acre-drift",
    chapter: 3,
    chapterHe: "ישראל",
    chapterEn: "Israel",
    trackId: "acre",
    mode: "drift",
    nameHe: "דריפט בחומות",
    nameEn: "Walls drift",
    night: true,
    unlockStars: 15,
    gold: 9500,
    silver: 5800,
    bronze: 3000,
  },
  {
    id: "hanikra-time",
    chapter: 6,
    chapterHe: "הצפון",
    chapterEn: "The North",
    trackId: "hanikra",
    mode: "time",
    nameHe: "המצוק הלבן",
    nameEn: "The white cliff",
    night: false,
    unlockStars: 16,
    gold: 90,
    silver: 112,
    bronze: 140,
    lineHe: "תמר: מנהרה ואז ים. אל תיכנס לקיר.",
    lineEn: "Tamar: Tunnel then sea. Don't kiss the wall.",
  },
  {
    id: "haifa-quay",
    chapter: 6,
    chapterHe: "הצפון",
    chapterEn: "The North",
    trackId: "haifaport",
    mode: "heat",
    nameHe: "מרדף ברציפים",
    nameEn: "Quay heat",
    night: true,
    unlockStars: 16,
    gold: 110,
    silver: 140,
    bronze: 180,
    lineHe: "ארי: עגורנים וסמויים. תברח לבת גלים.",
    lineEn: "Ari: Cranes and unmarked cars. Break for Bat Galim.",
  },
  {
    id: "carmel-full",
    chapter: 6,
    chapterHe: "הצפון",
    chapterEn: "The North",
    trackId: "stellamaris",
    mode: "circuit",
    nameHe: "הכרמל מלמעלה",
    nameEn: "Carmel from the top",
    night: false,
    unlockStars: 18,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "מאיה: ירידה ארוכה. הבלם הוא החבר שלך.",
    lineEn: "Maya: Long descent. The brake is your friend.",
  },
  {
    id: "kinneret-lap",
    chapter: 6,
    chapterHe: "הצפון",
    chapterEn: "The North",
    trackId: "tiberias",
    mode: "circuit",
    nameHe: "הקפה על הכנרת",
    nameEn: "Kinneret lap",
    night: false,
    unlockStars: 18,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "נועם: מים מימין. אל תיפול פנימה.",
    lineEn: "Noam: Water on the right. Don't drop in.",
  },
  {
    id: "golan-98",
    chapter: 6,
    chapterHe: "הצפון",
    chapterEn: "The North",
    trackId: "golan",
    mode: "time",
    nameHe: "כביש 98",
    nameEn: "Route 98",
    night: false,
    unlockStars: 19,
    gold: 94,
    silver: 116,
    bronze: 145,
    lineHe: "תמר: בזלת ורוח. שמור קו.",
    lineEn: "Tamar: Basalt and wind. Hold the line.",
  },
  {
    id: "hermon-climb",
    chapter: 6,
    chapterHe: "הצפון",
    chapterEn: "The North",
    trackId: "hermon",
    mode: "drift",
    nameHe: "דריפט בשלג",
    nameEn: "Snow drift",
    night: false,
    unlockStars: 20,
    gold: 8000,
    silver: 4800,
    bronze: 2400,
    lineHe: "ארי: אחיזה חצי. הזווית תעשה את השאר.",
    lineEn: "Ari: Half grip. The angle does the rest.",
  },
  {
    id: "hw6-run",
    chapter: 7,
    chapterHe: "העורקים",
    chapterEn: "The Arteries",
    trackId: "hw6",
    mode: "time",
    nameHe: "חוצה ישראל",
    nameEn: "Trans-Israel",
    night: false,
    unlockStars: 21,
    gold: 88,
    silver: 110,
    bronze: 138,
    lineHe: "מאיה: רחב ומהיר. אל תישן במחלף.",
    lineEn: "Maya: Wide and fast. Don't sleep at the interchange.",
  },
  {
    id: "hw2-coast",
    chapter: 7,
    chapterHe: "העורקים",
    chapterEn: "The Arteries",
    trackId: "hw2",
    mode: "circuit",
    nameHe: "כביש החוף",
    nameEn: "Coast road",
    night: true,
    unlockStars: 21,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "נועם: ים משמאל. שמור נתיב ימין.",
    lineEn: "Noam: Sea on the left. Hold the right lane.",
  },
  {
    id: "hw90-arava",
    chapter: 7,
    chapterHe: "העורקים",
    chapterEn: "The Arteries",
    trackId: "hw90",
    mode: "heat",
    nameHe: "מרדף בערבה",
    nameEn: "Arava heat",
    night: false,
    unlockStars: 22,
    gold: 120,
    silver: 155,
    bronze: 200,
    weather: "clear",
    lineHe: "ארי: 200 ק״מ של כלום. תברח דרומה.",
    lineEn: "Ari: 200km of nothing. Run south.",
  },
  {
    id: "petah-lap",
    chapter: 8,
    chapterHe: "השפלה",
    chapterEn: "The Plain",
    trackId: "petah",
    mode: "circuit",
    nameHe: "אם המושבות",
    nameEn: "Em HaMoshavot",
    night: false,
    unlockStars: 22,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "תמר: ז׳בוטינסקי רחב. אל תיכנס לקניון.",
    lineEn: "Tamar: Jabotinsky is wide. Don't enter the mall.",
  },
  {
    id: "rishon-wine",
    chapter: 8,
    chapterHe: "השפלה",
    chapterEn: "The Plain",
    trackId: "rishon",
    mode: "drift",
    nameHe: "דריפט ביקב",
    nameEn: "Winery drift",
    night: true,
    unlockStars: 23,
    gold: 8200,
    silver: 5000,
    bronze: 2600,
    lineHe: "מאיה: רוטשילד צר. זווית קצרה.",
    lineEn: "Maya: Rothschild is tight. Short angle.",
  },
  {
    id: "ashdod-heat",
    chapter: 8,
    chapterHe: "השפלה",
    chapterEn: "The Plain",
    trackId: "ashdod",
    mode: "heat",
    nameHe: "מרדף בנמל",
    nameEn: "Port heat",
    night: true,
    unlockStars: 23,
    gold: 115,
    silver: 145,
    bronze: 185,
    lineHe: "ארי: עגורנים ומכולות. תברח למרינה.",
    lineEn: "Ari: Cranes and containers. Break for the marina.",
  },
  {
    id: "ashkelon-walls",
    chapter: 8,
    chapterHe: "השפלה",
    chapterEn: "The Plain",
    trackId: "ashkelon",
    mode: "time",
    nameHe: "החומות",
    nameEn: "The walls",
    night: false,
    unlockStars: 24,
    gold: 92,
    silver: 114,
    bronze: 142,
    lineHe: "נועם: אבן וים. שמור קו על החומה.",
    lineEn: "Noam: Stone and sea. Hold the wall line.",
  },
  {
    id: "scopus-climb",
    chapter: 9,
    chapterHe: "ירושלים רבתי",
    chapterEn: "Greater Jerusalem",
    trackId: "scopus",
    mode: "circuit",
    nameHe: "הצופים",
    nameEn: "Scopus",
    night: false,
    unlockStars: 24,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "מאיה: ירידה ארוכה. הבלם שוב.",
    lineEn: "Maya: Long descent. The brake again.",
  },
  {
    id: "walls-loop",
    chapter: 9,
    chapterHe: "ירושלים רבתי",
    chapterEn: "Greater Jerusalem",
    trackId: "walls",
    mode: "time",
    nameHe: "סביב החומות",
    nameEn: "Around the walls",
    night: true,
    unlockStars: 25,
    gold: 96,
    silver: 118,
    bronze: 148,
    lineHe: "נועם: אבן חלקה בלילה. אל תיגע בחומה.",
    lineEn: "Noam: Smooth stone at night. Don't kiss the wall.",
  },
  {
    id: "modiin-431",
    chapter: 9,
    chapterHe: "ירושלים רבתי",
    chapterEn: "Greater Jerusalem",
    trackId: "modiin",
    mode: "knockout",
    nameHe: "431",
    nameEn: "431",
    night: false,
    unlockStars: 25,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "ארי: יער ואז מחלף. מי שנרדם יוצא.",
    lineEn: "Ari: Forest then interchange. Sleep and you're out.",
  },
  {
    id: "ramon-rim",
    chapter: 10,
    chapterHe: "הנגב",
    chapterEn: "The Negev",
    trackId: "ramon",
    mode: "circuit",
    nameHe: "שפת המכתש",
    nameEn: "Crater rim",
    night: false,
    unlockStars: 26,
    gold: 1,
    silver: 2,
    bronze: 3,
    weather: "hamsin",
    lineHe: "תמר: אל תיפול פנימה.",
    lineEn: "Tamar: Don't fall in.",
  },
  {
    id: "hw40-boker",
    chapter: 10,
    chapterHe: "הנגב",
    chapterEn: "The Negev",
    trackId: "hw40",
    mode: "time",
    nameHe: "שדה בוקר",
    nameEn: "Sde Boker",
    night: false,
    unlockStars: 26,
    gold: 98,
    silver: 122,
    bronze: 152,
    lineHe: "נועם: ישר, חם, ריק.",
    lineEn: "Noam: Straight, hot, empty.",
  },
  {
    id: "eilat-pass",
    chapter: 10,
    chapterHe: "הנגב",
    chapterEn: "The Negev",
    trackId: "eilatmtn",
    mode: "drift",
    nameHe: "המעבר האדום",
    nameEn: "The red pass",
    night: false,
    unlockStars: 28,
    gold: 8600,
    silver: 5200,
    bronze: 2800,
    lineHe: "מאיה: סיכות. זווית או קיר.",
    lineEn: "Maya: Hairpins. Angle or wall.",
  },
  {
    id: "gush-roam",
    chapter: 11,
    chapterHe: "גוש דן",
    chapterEn: "Gush Dan",
    trackId: "gushdan",
    mode: "roam",
    nameHe: "חותמות הגוש",
    nameEn: "Metro stamps",
    night: false,
    unlockStars: 8,
    gold: 150,
    silver: 210,
    bronze: 280,
    lineHe: "תמר: יפו עד הרצליה. אספי את כולם.",
    lineEn: "Tamar: Jaffa to Herzliya. Collect them all.",
  },
  {
    id: "gal-nazareth",
    chapter: 6,
    chapterHe: "הגליל",
    chapterEn: "The Galilee",
    trackId: "nazareth",
    mode: "circuit",
    nameHe: "סמטאות נצרת",
    nameEn: "Nazareth alleys",
    night: false,
    unlockStars: 16,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "תמר: אל תיגע בכנסייה.",
    lineEn: "Tamar: Don't clip the basilica.",
  },
  {
    id: "gal-tzfat",
    chapter: 6,
    chapterHe: "הגליל",
    chapterEn: "The Galilee",
    trackId: "tzfat",
    mode: "drift",
    nameHe: "סיכות צפת",
    nameEn: "Safed pins",
    night: true,
    unlockStars: 18,
    gold: 7200,
    silver: 4200,
    bronze: 2200,
    lineHe: "מאיה: ירידות. זווית.",
    lineEn: "Maya: Downhill. Angle.",
  },
  {
    id: "ds-masada",
    chapter: 8,
    chapterHe: "המדבר",
    chapterEn: "The desert",
    trackId: "masada",
    mode: "time",
    nameHe: "שביל הנחש",
    nameEn: "Snake path",
    night: false,
    unlockStars: 20,
    gold: 96,
    silver: 120,
    bronze: 150,
    weather: "hamsin",
    lineHe: "ארי: למעלה בלי לבלום.",
    lineEn: "Ari: Up without braking.",
  },
  {
    id: "tlv-batyam",
    chapter: 1,
    chapterHe: "רישיון תל אביב",
    chapterEn: "TLV license",
    trackId: "batyam",
    mode: "circuit",
    nameHe: "טיילת בת ים",
    nameEn: "Bat Yam promenade",
    night: false,
    unlockStars: 4,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "נועם: יפו באופק. שמור על הקו.",
    lineEn: "Noam: Jaffa on the horizon. Hold the line.",
  },
  {
    id: "cup-coast",
    chapter: 12,
    chapterHe: "גביע ישראל",
    chapterEn: "Israel Cup",
    trackId: "hw2",
    mode: "circuit",
    nameHe: "גמר החוף",
    nameEn: "Coast final",
    night: true,
    unlockStars: 36,
    gold: 1,
    silver: 2,
    bronze: 3,
    weather: "clear",
    lineHe: "נועם: כביש 2 בלילה. זה הגביע.",
    lineEn: "Noam: Highway 2 at night. This is the cup.",
  },
  {
    id: "cup-capital",
    chapter: 12,
    chapterHe: "גביע ישראל",
    chapterEn: "Israel Cup",
    trackId: "walls",
    mode: "knockout",
    nameHe: "גמר הבירה",
    nameEn: "Capital final",
    night: true,
    unlockStars: 38,
    gold: 1,
    silver: 2,
    bronze: 3,
    lineHe: "מאיה: מי שנרדם על החומה יוצא.",
    lineEn: "Maya: Sleep on the wall and you're out.",
  },
  {
    id: "cup-south",
    chapter: 12,
    chapterHe: "גביע ישראל",
    chapterEn: "Israel Cup",
    trackId: "hw90",
    mode: "time",
    nameHe: "גמר הערבה",
    nameEn: "Arava final",
    night: false,
    unlockStars: 40,
    gold: 92,
    silver: 116,
    bronze: 148,
    weather: "hamsin",
    lineHe: "ארי: חמסין וחום. שעון נקי.",
    lineEn: "Ari: Hamsin and heat. A clean clock.",
  },
  {
    id: "cup-final",
    chapter: 12,
    chapterHe: "גביע ישראל",
    chapterEn: "Israel Cup",
    trackId: "telaviv",
    mode: "heat",
    nameHe: "גביע ישראל",
    nameEn: "Israel Cup",
    night: true,
    unlockStars: 44,
    gold: 105,
    silver: 135,
    bronze: 175,
    lineHe: "תמר: עזריאלי בלילה. תברח ותשמור על הגביע.",
    lineEn: "Tamar: Azrieli at night. Run and keep the cup.",
  },
];

export function dailyEvent(d = new Date()): CareerEvent {
  const ch = todayChallenge(d);
  const timeGold = 85;
  return {
    id: `daily-${ch.key}`,
    chapter: 0,
    chapterHe: "אתגר היום",
    chapterEn: "Daily challenge",
    trackId: ch.trackId,
    mode: ch.mode,
    nameHe: "אתגר היום",
    nameEn: "Daily challenge",
    night: ch.night,
    unlockStars: 0,
    gold: ch.mode === "time" ? timeGold : ch.mode === "drift" ? 7000 : ch.mode === "heat" ? timeGold + 20 : 1,
    silver: ch.mode === "time" ? timeGold + 22 : ch.mode === "drift" ? 4200 : ch.mode === "heat" ? timeGold + 50 : 2,
    bronze: ch.mode === "time" ? timeGold + 48 : ch.mode === "drift" ? 2200 : ch.mode === "heat" ? timeGold + 90 : 3,
    weather: ch.weather,
  };
}

export function getEvent(id: string) {
  if (id.startsWith("daily-")) return dailyEvent();
  if (id.startsWith("weekly-")) return weeklyEvent();
  return CAREER.find((e) => e.id === id) ?? null;
}

export function weeklyKey(d = new Date()) {
  const t = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  const day = t.getUTCDay() || 7;
  t.setUTCDate(t.getUTCDate() + 4 - day);
  const yearStart = new Date(Date.UTC(t.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((t.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
  return `${t.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
}

export function weeklyEvent(d = new Date()): CareerEvent {
  const key = weeklyKey(d);
  const ch = todayChallenge(new Date(d.getFullYear(), d.getMonth(), d.getDate() + 3));
  return {
    id: `weekly-${key}`,
    chapter: 0,
    chapterHe: "אליפות השבוע",
    chapterEn: "Weekly cup",
    trackId: ch.trackId,
    mode: ch.mode === "heat" ? "circuit" : ch.mode,
    nameHe: "אליפות השבוע",
    nameEn: "Weekly cup",
    night: true,
    unlockStars: 0,
    gold: ch.mode === "time" ? 78 : ch.mode === "drift" ? 8000 : 1,
    silver: ch.mode === "time" ? 98 : ch.mode === "drift" ? 4800 : 2,
    bronze: ch.mode === "time" ? 122 : ch.mode === "drift" ? 2400 : 3,
    weather: ch.weather,
  };
}

export function starsFor(ev: CareerEvent, r: RaceResult): number {
  if (ev.mode === "heat") {
    if (r.busted) return 0;
    if (r.heatMax < 0.48) return 3;
    if (r.totalTime <= ev.gold) return 3;
    if (r.heatMax < 0.82) return 2;
    return 1;
  }
  if (ev.mode === "drift") {
    if (r.driftScore >= ev.gold) return 3;
    if (r.driftScore >= ev.silver) return 2;
    if (r.driftScore >= ev.bronze) return 1;
    return 0;
  }
  if (ev.mode === "time" || ev.mode === "roam") {
    if (r.totalTime <= ev.gold) return 3;
    if (r.totalTime <= ev.silver) return 2;
    if (r.totalTime <= ev.bronze) return 1;
    return 0;
  }
  if (r.place <= 1) return 3;
  if (r.place <= 2) return 2;
  if (r.place <= 3) return 1;
  return 0;
}

export function maxStars() {
  return CAREER.length * 3;
}

export function chapters() {
  const map = new Map<number, { he: string; en: string; events: CareerEvent[] }>();
  for (const ev of CAREER) {
    const cur = map.get(ev.chapter) ?? { he: ev.chapterHe, en: ev.chapterEn, events: [] };
    cur.events.push(ev);
    map.set(ev.chapter, cur);
  }
  return [...map.entries()].sort((a, b) => a[0] - b[0]).map(([, v]) => v);
}
