import type { CarDef, CarId } from "./types";

export const CARS: CarDef[] = [
  {
    id: "sabra",
    nameHe: "צבר",
    nameEn: "Sabra",
    tagline: "סדאן משפחתי · 0–100 ב־8.4 שנ׳",
    color: 0xf2eee8,
    accent: 0x1a3a6a,
    maxSpeed: 53,
    accel: 6.2,
    brake: 9.2,
    turnRate: 1.85,
    grip: 0.9,
    drag: 0.55,
    mass: 1.12,
    body: "gt",
    zeroTo100: 8.4,
  },
  {
    id: "carmel",
    nameHe: "כרמל T",
    nameEn: "Carmel T",
    tagline: "האצ׳בק חם · 0–100 ב־6.6 שנ׳",
    color: 0xc42c24,
    accent: 0x1a1010,
    maxSpeed: 64,
    accel: 6.8,
    brake: 10.4,
    turnRate: 2.12,
    grip: 0.92,
    drag: 0.58,
    mass: 0.96,
    body: "hatch",
    zeroTo100: 6.6,
  },
  {
    id: "kfir",
    nameHe: "כפיר V8",
    nameEn: "Kfir V8",
    tagline: "קופה אמריקאית · 0–100 ב־4.9 שנ׳",
    color: 0x1a2a48,
    accent: 0xc8a24a,
    maxSpeed: 72,
    accel: 8.2,
    brake: 9.6,
    turnRate: 1.68,
    grip: 0.84,
    drag: 0.46,
    mass: 1.34,
    body: "muscle",
    nitroStart: 0.28,
    zeroTo100: 4.9,
  },
  {
    id: "negev",
    nameHe: "נגב",
    nameEn: "Negev",
    tagline: "ראלי · אחיזה בחצץ · 0–100 ב־5.8 שנ׳",
    color: 0xc4a06a,
    accent: 0x3a2814,
    maxSpeed: 58,
    accel: 7.4,
    brake: 10,
    turnRate: 1.92,
    grip: 0.97,
    drag: 0.5,
    mass: 1.24,
    body: "rally",
    zeroTo100: 5.8,
  },
  {
    id: "yam",
    nameHe: "ים סוף",
    nameEn: "Yam Suf",
    tagline: "ספורט נמוך · 0–100 ב־3.5 שנ׳",
    color: 0x0c1420,
    accent: 0x6ec8c4,
    maxSpeed: 86,
    accel: 10.4,
    brake: 12.4,
    turnRate: 1.78,
    grip: 0.88,
    drag: 0.4,
    mass: 0.94,
    body: "super",
    zeroTo100: 3.5,
  },
];

export function getCar(id: CarId | string) {
  return CARS.find((x) => x.id === id) ?? CARS[0];
}

export const RIVALS = [
  { he: "נועם כהן", en: "Noam Cohen" },
  { he: "מאיה לוי", en: "Maya Levi" },
  { he: "ארי מזרחי", en: "Ari Mizrahi" },
  { he: "תמר בן דוד", en: "Tamar Ben-David" },
] as const;
