import { defineTrack } from "../track-schema";

export default defineTrack({
    id: "brooklynbridge",
    nameHe: "גשר ברוקלין",
    nameEn: "Brooklyn Bridge",
    city: "nyc",
    cityHe: "ניו יורק",
    cityEn: "New York",
    lengthHint: "3 הקפות · איסט ריבר",
    description: "מגדלי הגותיקה מעל האיסט ריבר — סיטי הול, דאמבו, ואן וורלד טרייד ופסל החירות. בהשראת המקום, לא מפה ולא GIS.",
    descriptionEn: "Gothic towers over the East River — City Hall, DUMBO, One World Trade and the Statue of Liberty. Inspired by the place — not a map, not GIS.",
    image: "/tracks/brooklynbridge.jpg",
    width: 12.4,
    seed: 1883,
    theme: "manhattan",
    ground: 0x6a6860,
    sand: 0xb0a488,
    sky: {
      elevation: 8.2,
      azimuth: 244,
      turbidity: 5.8,
      rayleigh: 1.7,
      mieCoefficient: 0.0046,
      mieDirectionalG: 0.86,
      exposure: 0.82,
      fog: 0x6a7480,
      fogDensity: 0.0038,
    },
    water: { x: 10, z: 18, w: 92, d: 160, color: 0x163848 },
    checkpointCount: 10,
    points: [
      { x: -58, z: 10 },
      { x: -22, z: 4 },
      { x: 16, z: -2 },
      { x: 52, z: -8 },
      { x: 88, z: -22 },
      { x: 112, z: 4 },
      { x: 108, z: 36 },
      { x: 78, z: 52 },
      { x: 40, z: 58 },
      { x: 4, z: 52 },
      { x: -36, z: 46 },
      { x: -72, z: 38 },
      { x: -98, z: 22 },
      { x: -100, z: 12 },
    ],
    elevation: (t) => {
      const bb = Math.exp(-(((t - 0.14) / 0.1) ** 2)) * 16.5;
      const mb = Math.exp(-(((t - 0.58) / 0.1) ** 2)) * 11.5;
      return bb + mb;
    },
    streets: [
      { from: 0.0, to: 0.22, he: "גשר ברוקלין", en: "Brooklyn Bridge" },
      { from: 0.22, to: 0.36, he: "קדמן פלאזה", en: "Cadman Plaza" },
      { from: 0.36, to: 0.5, he: "דאמבו · פולטון", en: "DUMBO · Fulton" },
      { from: 0.5, to: 0.64, he: "גשר מנהטן", en: "Manhattan Bridge" },
      { from: 0.64, to: 0.78, he: "סאות סטריט סיפורט", en: "South Street Seaport" },
      { from: 0.78, to: 0.9, he: "פיננשל דיסטריקט", en: "Financial District" },
      { from: 0.9, to: 1, he: "סיטי הול · פארק רואו", en: "City Hall · Park Row" },
    ],
    pois: [
      { x: -22, z: 4, r: 28, he: "מגדל מנהטן", en: "Manhattan Tower" },
      { x: 52, z: -8, r: 28, he: "מגדל ברוקלין", en: "Brooklyn Tower" },
      { x: 112, z: 8, r: 32, he: "דאמבו", en: "DUMBO" },
      { x: -88, z: -8, r: 40, he: "ואן וורלד טרייד", en: "One World Trade" },
      { x: -70, z: 8, r: 28, he: "וולוורת'", en: "Woolworth Building" },
      { x: -130, z: -70, r: 48, he: "פסל החירות", en: "Statue of Liberty" },
      { x: -72, z: 38, r: 28, he: "הסיפורט", en: "South Street Seaport" },
    ],
  });
