import { defineTrack } from "../track-schema";

export default defineTrack({
    id: "centralpark",
    nameHe: "סנטרל פארק",
    nameEn: "Central Park Drive",
    city: "nyc",
    cityHe: "ניו יורק",
    cityEn: "New York",
    lengthHint: "3 הקפות · פארק דרייב",
    description: "הלולאה ההיסטורית בתוך הפארק — גרנד ארמי פלאזה, בזסדה, מאגר המים והגוגנהיים. בהשראת המקום, לא מפה ולא GIS.",
    descriptionEn: "The historic Park Drive loop — Grand Army Plaza, Bethesda, the Reservoir and the Guggenheim. Inspired by the place — not a map, not GIS.",
    image: "/tracks/centralpark.jpg",
    width: 12.6,
    seed: 1858,
    theme: "park",
    ground: 0x4a6248,
    sand: 0xc4b090,
    sky: {
      elevation: 18,
      azimuth: 228,
      turbidity: 4.8,
      rayleigh: 1.55,
      mieCoefficient: 0.0042,
      mieDirectionalG: 0.8,
      exposure: 0.98,
      fog: 0xb8c4b0,
      fogDensity: 0.004,
    },
    water: { x: -14, z: -6, w: 52, d: 40, color: 0x1a5858 },
    waters: [
      { x: -14, z: -6, w: 52, d: 40, color: 0x1a5858 },
      { x: 4, z: 86, w: 58, d: 50, color: 0x1c6068 },
    ],
    clearZones: [{ x: 0, z: 8, w: 92, d: 250 }],
    checkpointCount: 10,
    points: [
      { x: 0, z: -118 },
      { x: 38, z: -92 },
      { x: 48, z: -48 },
      { x: 50, z: -8 },
      { x: 52, z: 32 },
      { x: 48, z: 72 },
      { x: 36, z: 108 },
      { x: 8, z: 132 },
      { x: -28, z: 118 },
      { x: -48, z: 78 },
      { x: -50, z: 32 },
      { x: -48, z: -12 },
      { x: -42, z: -58 },
      { x: -28, z: -102 },
    ],
    elevation: (t) => 0.8 * Math.sin(t * Math.PI * 5) + 1.4 * Math.sin(t * Math.PI * 2),
    streets: [
      { from: 0.0, to: 0.14, he: "גרנד ארמי פלאזה", en: "Grand Army Plaza" },
      { from: 0.14, to: 0.28, he: "איסט דרייב · גן החיות", en: "East Drive · Zoo" },
      { from: 0.28, to: 0.42, he: "בזסדה טרס", en: "Bethesda Terrace" },
      { from: 0.42, to: 0.56, he: "המוזיאון המטרופוליטן", en: "The Met" },
      { from: 0.56, to: 0.7, he: "מאגר המים", en: "The Reservoir" },
      { from: 0.7, to: 0.82, he: "הארלם מיר", en: "Harlem Meer" },
      { from: 0.82, to: 0.92, he: "וסט דרייב", en: "West Drive" },
      { from: 0.92, to: 1, he: "קולומבוס סירקל", en: "Columbus Circle" },
    ],
    pois: [
      { x: 8, z: -8, r: 28, he: "מזרקת בזסדה", en: "Bethesda Fountain" },
      { x: -18, z: 2, r: 24, he: "גשר הקשת", en: "Bow Bridge" },
      { x: -6, z: 28, r: 26, he: "טירת בלוודיר", en: "Belvedere Castle" },
      { x: 72, z: 38, r: 36, he: "המטרופוליטן", en: "The Met" },
      { x: 72, z: 88, r: 32, he: "הגוגנהיים", en: "Guggenheim" },
      { x: -72, z: -8, r: 28, he: "הדקוטה", en: "The Dakota" },
      { x: -48, z: -122, r: 32, he: "קולומבוס סירקל", en: "Columbus Circle" },
      { x: 12, z: -148, r: 30, he: "מלון פלאזה", en: "The Plaza" },
    ],
  });
