import { defineTrack } from "../track-schema";

export default defineTrack({
    id: "manhattan",
    nameHe: "הקפת מנהטן",
    nameEn: "Manhattan Loop",
    city: "nyc",
    cityHe: "ניו יורק",
    cityEn: "New York",
    lengthHint: "3 הקפות · האי כולו",
    description: "FDR, נהר הארלם והנרי הדסון — הקפה מלאה סביב האי עם קו הרקיע כולו. בהשראת המקום, לא מפה ולא GIS.",
    descriptionEn: "FDR Drive, Harlem River and the Henry Hudson — a full lap of the island and its skyline. Inspired by the place — not a map, not GIS.",
    image: "/tracks/manhattan.jpg",
    width: 15.2,
    seed: 1626,
    theme: "manhattan",
    ground: 0x5c5a56,
    sand: 0xa09888,
    sky: {
      elevation: 14,
      azimuth: 236,
      turbidity: 4.4,
      rayleigh: 1.6,
      mieCoefficient: 0.004,
      mieDirectionalG: 0.84,
      exposure: 0.9,
      fog: 0x8a96a4,
      fogDensity: 0.0032,
    },
    water: { x: -122, z: 0, w: 118, d: 420, color: 0x163850 },
    waters: [
      { x: -122, z: 0, w: 118, d: 420, color: 0x163850 },
      { x: 120, z: 0, w: 118, d: 420, color: 0x1a4050 },
      { x: 0, z: -228, w: 280, d: 96, color: 0x153848 },
    ],
    clearZones: [{ x: 0, z: 88, w: 58, d: 92 }],
    checkpointCount: 12,
    points: [
      { x: 0, z: -168 },
      { x: 38, z: -148 },
      { x: 52, z: -110 },
      { x: 58, z: -60 },
      { x: 62, z: -10 },
      { x: 64, z: 40 },
      { x: 60, z: 90 },
      { x: 52, z: 138 },
      { x: 18, z: 168 },
      { x: -22, z: 164 },
      { x: -52, z: 130 },
      { x: -60, z: 80 },
      { x: -62, z: 30 },
      { x: -58, z: -20 },
      { x: -50, z: -80 },
      { x: -32, z: -130 },
      { x: -8, z: -160 },
    ],
    elevation: (t) => 0.6 * Math.sin(t * Math.PI * 8) + (t > 0.48 && t < 0.62 ? 2.2 : 0),
    streets: [
      { from: 0.0, to: 0.1, he: "באטרי פארק", en: "Battery Park" },
      { from: 0.1, to: 0.22, he: "FDR · גשר ברוקלין", en: "FDR · Brooklyn Bridge" },
      { from: 0.22, to: 0.34, he: "FDR · איסט וילג'", en: "FDR · East Village" },
      { from: 0.34, to: 0.46, he: "FDR · האו\"ם", en: "FDR · United Nations" },
      { from: 0.46, to: 0.58, he: "קווינסבורו", en: "Queensboro" },
      { from: 0.58, to: 0.7, he: "נהר הארלם", en: "Harlem River" },
      { from: 0.7, to: 0.82, he: "הנרי הדסון", en: "Henry Hudson" },
      { from: 0.82, to: 0.92, he: "ריברסייד · 42", en: "Riverside · 42nd" },
      { from: 0.92, to: 1, he: "צ'לסי · הולנד", en: "Chelsea · Holland" },
    ],
    pois: [
      { x: -40, z: -208, r: 48, he: "פסל החירות", en: "Statue of Liberty" },
      { x: -18, z: -128, r: 40, he: "ואן וורלד טרייד", en: "One World Trade" },
      { x: -6, z: -48, r: 28, he: "פלאטאיירון", en: "Flatiron" },
      { x: 8, z: 8, r: 36, he: "אמפייר סטייט", en: "Empire State" },
      { x: 32, z: 22, r: 32, he: "קרייזלר", en: "Chrysler Building" },
      { x: 52, z: 36, r: 30, he: "האומות המאוחדות", en: "United Nations" },
      { x: -12, z: 18, r: 28, he: "טיימס סקוואר", en: "Times Square" },
      { x: 0, z: 88, r: 50, he: "סנטרל פארק", en: "Central Park" },
    ],
  });
