import { defineTrack } from "../track-schema";

export default defineTrack({
    id: "timessquare",
    nameHe: "טיימס סקוואר",
    nameEn: "Times Square",
    city: "nyc",
    cityHe: "ניו יורק",
    cityEn: "New York",
    lengthHint: "3 הקפות · ברודוויי",
    description: "הקניון הניאון — טיימס סקוואר, רוקפלר, הספרייה הציבורית ומגדל אמפייר סטייט. בהשראת המקום, לא מפה ולא GIS.",
    descriptionEn: "The neon canyon — Times Square, Rockefeller, the Public Library and the Empire State. Inspired by the place — not a map, not GIS.",
    image: "/tracks/timessquare.jpg",
    width: 13.2,
    seed: 1904,
    theme: "manhattan",
    ground: 0x5a5854,
    sand: 0xa8a090,
    sky: {
      elevation: 5.5,
      azimuth: 252,
      turbidity: 5.4,
      rayleigh: 1.4,
      mieCoefficient: 0.005,
      mieDirectionalG: 0.9,
      exposure: 0.76,
      fog: 0x3a3848,
      fogDensity: 0.0052,
    },
    checkpointCount: 8,
    points: [
      { x: 6, z: 0 },
      { x: 46, z: 2 },
      { x: 62, z: 8 },
      { x: 56, z: 46 },
      { x: 20, z: 52 },
      { x: -4, z: 58 },
      { x: -8, z: 92 },
      { x: -46, z: 86 },
      { x: -54, z: 36 },
      { x: -50, z: 2 },
      { x: -22, z: -4 },
      { x: 2, z: -28 },
    ],
    elevation: (t) => 0.4 * Math.sin(t * Math.PI * 6),
    streets: [
      { from: 0.0, to: 0.16, he: "השדרה השביעית · 42", en: "7th Ave · 42nd" },
      { from: 0.16, to: 0.3, he: "רחוב 42 · בראיינט פארק", en: "42nd · Bryant Park" },
      { from: 0.3, to: 0.44, he: "השדרה החמישית", en: "Fifth Avenue" },
      { from: 0.44, to: 0.58, he: "ברודוויי", en: "Broadway" },
      { from: 0.58, to: 0.72, he: "רוקפלר סנטר", en: "Rockefeller Center" },
      { from: 0.72, to: 0.86, he: "השדרה השמינית", en: "8th Avenue" },
      { from: 0.86, to: 1, he: "פורט אותוריטי", en: "Port Authority" },
    ],
    pois: [
      { x: 2, z: 10, r: 28, he: "ואן טיימס סקוואר", en: "One Times Square" },
      { x: 0, z: 36, r: 22, he: "כיכר דאפי · TKTS", en: "Duffy Square · TKTS" },
      { x: 8, z: 98, r: 36, he: "רוקפלר סנטר", en: "Rockefeller Center" },
      { x: 68, z: 6, r: 30, he: "הספרייה הציבורית", en: "NY Public Library" },
      { x: 18, z: -88, r: 42, he: "אמפייר סטייט", en: "Empire State" },
      { x: 78, z: -40, r: 36, he: "קרייזלר", en: "Chrysler Building" },
      { x: -52, z: 4, r: 28, he: "פורט אותוריטי", en: "Port Authority" },
    ],
  });
