// Generated by RSH-033. Keeps accepted RSH-007/RSH-032 physics and accel hashes exact.
const RECORDS = {
  "src/game/physics.ts": {
    "physics-version": "export const PHYSICS_VERSION = 6;\n",
  },
  "src/game/vehicle.ts": {
    "gear-dump": "      if (g !== this.gear && racing) this.speed *= 0.94;\n",
    "launch-law": "        const v100 = 27.778;\n        const t100 = Math.max(3.2, stats.zeroTo100 ?? 8);\n        const pull = throttle * (v100 / t100) * mass * wx.long * surf.long * (boosting ? 1.08 : 1) * (this.drafting ? 1.05 : 1);\n        const top = vAbs <= v100 ? 1 : Math.max(0.02, driveCurve);\n        this.speed += (pull / mass) * top * dt;\n",
  },
  "scripts/accel-smoke.mjs": {
    "claim-note": "    \"CI fails on acceleration regression. zeroTo100 claim mismatches remain explicit and are calibrated in RSH-033.\",\n",
    "claim-fail": "if (claimGaps.length) {\n  console.warn(\"qa:accel known zeroTo100 claim gaps (RSH-033):\\n\" + claimGaps.join(\"\\n\"));\n}\n",
  },
};

function escapeRegex(value) {
  return value.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&");
}

export function stripRsh033Overlay(path, source) {
  const records = RECORDS[path] ?? {};
  let normalized = source;
  for (const [id, legacy] of Object.entries(records)) {
    const pattern = new RegExp(
      `^[ \\t]*// RSH-033-OVERLAY-BEGIN:${escapeRegex(id)}\\n[\\s\\S]*?^[ \\t]*// RSH-033-OVERLAY-END:${escapeRegex(id)}\\n?`,
      "m",
    );
    const matches = normalized.match(new RegExp(pattern.source, "gm")) ?? [];
    if (matches.length !== 1) {
      throw new Error(`RSH-033 overlay ${path}:${id} is missing or duplicated`);
    }
    normalized = normalized.replace(pattern, legacy);
  }
  return normalized;
}

export const RSH033_OVERLAY_RECORDS = Object.freeze(RECORDS);
export const RSH033_STRIP_PHYSICS_SHA256 = "cbff35aa2e2e4b509decf38e9f1ca3d262667675af81e0352ba02f460f5723c1";
export const RSH033_STRIP_ACCEL_SHA256 = "3dd2499741a581b13c97f3f6f51f0861228c9b26c1964c0970f267c4aff4fb50";
