// Generated by RSH-019. Keeps accepted RSH-015/RSH-017 reconstruction exact.
const RECORDS = {
  "src/game/world.ts": {
    "world-disposal-import": "import { assembleWorld } from \"./world-core\";\n",
    "world-disposed-state": "  const group = new THREE.Group();\n  const bag: Disposable[] = [];\n",
    "world-reflector-disposal": "    bag.push({ dispose() {\n      mirror?.dispose();\n      mirror?.geometry.dispose();\n    } });\n",
    "world-dispose": "    dispose() {\n      for (const d of bag) d.dispose();\n    },\n"
  },
  "src/game/engine.ts": {
    "engine-disposal-imports": "import { ResourceRegistry } from \"../rendering/ResourceRegistry\";\n",
    "engine-car-disposer-import": "import { createCarVisual, pulsePolice, setCarLights, updateCarVisual, applyDamage, type CarVisual } from \"./car-mesh\";\n",
    "engine-csm-lease": "      this.leases.retain(\"csm\", () => {\n        this.csm?.remove();\n        this.csm?.dispose();\n        this.csm = null;\n      });\n",
    "engine-probe-lease": "      this.leases.retain(\"probe-rt\", () => {\n        this.probeRT?.dispose();\n        this.probeRT = null;\n      });\n",
    "engine-dispose": "  dispose() {\n    this.disposed = true;\n    this.renderer.setAnimationLoop(null);\n    this.canvas.removeEventListener(\"webglcontextlost\", this.onContextLost);\n    this.canvas.removeEventListener(\"webglcontextrestored\", this.onContextRestored);\n    window.removeEventListener(\"resize\", this.onResize);\n    if (this.booted) {\n      this.input.dispose();\n      this.audio.dispose();\n      this.leases.release(\"csm\");\n      this.world.dispose();\n      this.leases.disposeAll();\n      this.sparks.geometry.dispose();\n      (this.sparks.material as THREE.Material).dispose();\n      if (this.blobs[0]) {\n        this.blobs[0].geometry.dispose();\n        (this.blobs[0].material as THREE.Material).dispose();\n      }\n      this.gate.geometry.dispose();\n      (this.gate.material as THREE.Material).dispose();\n      this.skidMesh.geometry.dispose();\n      (this.skidMesh.material as THREE.Material).dispose();\n      this.smokeMesh.geometry.dispose();\n      (this.smokeMesh.material as THREE.Material).dispose();\n      this.boostPts.geometry.dispose();\n      (this.boostPts.material as THREE.Material).dispose();\n      if (this.rainMesh) {\n        this.rainMesh.geometry.dispose();\n        (this.rainMesh.material as THREE.Material).dispose();\n      }\n      this.clearRoadblock();\n    }\n    this.leases.disposeAll();\n    this.gfx.dispose();\n    if (import.meta.env.DEV || import.meta.env.VITE_QA === \"1\") {\n      delete window.__controlsTest;\n      delete window.render_game_to_text;\n    }\n  }\n}"
  },
  "src/game/engine/rendering-adapter.ts": {
    "adapter-upgrade-post": "      const post = createPost(this.renderer, this.scene, this.camera, this.world.night, this.lite);\n      this.leases.release(\"post\");\n      this.post.dispose();\n      this.post = post;\n      this.leases.retain(\"post\", () => this.post.dispose());\n",
    "adapter-capture-env": "    try {\n      const size = this.trackDef.id === \"ayalon\" ? 128 : 96;\n      const rt = new THREE.WebGLCubeRenderTarget(size);\n      const cam = new THREE.CubeCamera(4, 400, rt);\n      cam.position.set(this.player.x, this.player.y + 26, this.player.z);\n      const hidden: THREE.Object3D[] = [];\n      const stash = (g: THREE.Object3D) => {\n        if (g.visible) {\n          g.visible = false;\n          hidden.push(g);\n        }\n      };\n      for (const v of this.visuals) stash(v.group);\n      for (const v of this.trafficVis) stash(v.group);\n      for (const v of this.copVis) stash(v.group);\n      cam.update(this.renderer, this.scene);\n      for (const g of hidden) g.visible = true;\n      this.leases.release(\"boot-env\");\n      this.scene.environment = rt.texture;\n      this.leases.retain(\"boot-env\", () => rt.dispose());\n      return true;\n    } catch {\n      return false;\n    }",
    "adapter-env-lease": "    this.leases.release(\"env-rt\");\n    this.envRT = rt;\n    this.leases.retain(\"env-rt\", () => this.envRT.dispose());\n"
  }
};

function escapeRegex(value) {
  return value.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&");
}

export function stripRsh019Overlay(path, source) {
  const records = RECORDS[path] ?? {};
  let normalized = source;
  for (const [id, legacy] of Object.entries(records)) {
    const pattern = new RegExp(
      `^[ \\t]*// RSH-019-OVERLAY-BEGIN:${escapeRegex(id)}\\n[\\s\\S]*?^[ \\t]*// RSH-019-OVERLAY-END:${escapeRegex(id)}\\n?`,
      "m",
    );
    const matches = normalized.match(new RegExp(pattern.source, "gm")) ?? [];
    if (matches.length !== 1) {
      throw new Error(`RSH-019 overlay ${path}:${id} is missing or duplicated`);
    }
    normalized = normalized.replace(pattern, legacy);
  }
  return normalized;
}

export const RSH019_OVERLAY_RECORDS = Object.freeze(RECORDS);
