// Generated by RSH-036. Keeps accepted RSH-017/RSH-019 adapter bytes exact.
const RECORDS = {
  "src/game/engine/rendering-adapter.ts": {
    "chase-rest-geometry": "    let follow = 9.2 + clamp(Math.abs(p.speed) / 22, 0, 2.6);\n    let height = 2.28;\n",
  },
};

export const LOCKED_CHASE_FOLLOW_BASE = 7.4;
export const LOCKED_CHASE_FOLLOW_SPEED_DIV = 22;
export const LOCKED_CHASE_FOLLOW_CLAMP = 2.2;
export const LOCKED_CHASE_HEIGHT = 1.92;
export const DRIFTED_CHASE_FOLLOW_BASE = 9.2;
export const DRIFTED_CHASE_FOLLOW_CLAMP = 2.6;
export const DRIFTED_CHASE_HEIGHT = 2.28;
export const ACCEPTED_RENDERING_ADAPTER_SHA256 = "947ca69a89f12550a4ba5c631f2004598dec8849368a762b29ed9d681a2d7132";
export const GOLDEN_ATTRIBUTION_CAMERA_DY = 0.36;
export const GOLDEN_ATTRIBUTION_CAMERA_DZ = -1.8;

function escapeRegex(value) {
  return value.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&");
}

export function chaseFollowDistance(speed, { base = LOCKED_CHASE_FOLLOW_BASE, clampMax = LOCKED_CHASE_FOLLOW_CLAMP } = {}) {
  const value = Math.abs(Number(speed));
  const extra = Number.isFinite(value) ? Math.min(Math.max(value / LOCKED_CHASE_FOLLOW_SPEED_DIV, 0), clampMax) : 0;
  return base + extra;
}

export function driftedChaseFollowDistance(speed) {
  return chaseFollowDistance(speed, { base: DRIFTED_CHASE_FOLLOW_BASE, clampMax: DRIFTED_CHASE_FOLLOW_CLAMP });
}

export function stripRsh036Overlay(path, source) {
  const records = RECORDS[path];
  if (!records) return source;
  let normalized = source;
  for (const [id, legacy] of Object.entries(records)) {
    const pattern = new RegExp(
      `^[ \\t]*// RSH-036-OVERLAY-BEGIN:${escapeRegex(id)}\\n[\\s\\S]*?^[ \\t]*// RSH-036-OVERLAY-END:${escapeRegex(id)}\\n?`,
      "m",
    );
    const matches = normalized.match(new RegExp(pattern.source, "gm")) ?? [];
    if (matches.length !== 1) {
      throw new Error(`RSH-036 overlay ${path}:${id} is missing or duplicated`);
    }
    normalized = normalized.replace(pattern, legacy);
  }
  return normalized;
}

export const RSH036_OVERLAY_RECORDS = Object.freeze(RECORDS);
